### ISSUE TITLE
Нарушен принцип единственной ответственности в методе createGood сервиса InMemoryGoodService

### ISSUE THREAD

**Issue by stepanenko-dev** [Van-Stepanenko/MyWarehouse#2]
https://github.com/Van-Stepanenko/MyWarehouse/blob/510eac91317f59ab355b77b63bfb6ce0bc46341e/src/main/java/dev/stepanenko/my/warehouse/domain/InMemoryGoodService.java#L24

2 ответственности в одном методе - создание Good и сохранение. Желательно разделить. Вынеси создание объекта в другой метод этого класса или внутрь класса Good или примени паттерн Builder (не через аннотацию Lombok а напиши руками).

**Comment by Van-Stepanenko** [comment]
Закрыта в рамках пуллреквеста номер 3
